### ISSUE TITLE
Error in angular 11

### ISSUE THREAD

**Issue by adam-abdulaev** [Davidmnj91/mnj-ngx-pdfviewer#1]
Hi David. First of all, I want to say that you did a great job! Your project looks really cool. I have been working with pdfjs for the last months too. While researching your project, I found that you are importing PDFJS
with this line import * as PDFJS from 'pdfjs-dist';

When I previously tried to do the same in my Angular 11 project, I got a build error. Have you faced such a problem and how did you solve it? Thank you in advance.
![image](https://user-images.githubusercontent.com/84326043/133091303-75bff59a-6dd3-4ad3-863a-2a5fb6e10fc3.png)

**Comment by Davidmnj91** [comment]
Hi, probably is due to the missing allowJsDependencies in the angular.json file
Everytime you need to import / work with a pure JavaScript library you need to add the entry there
Take this as example: 
`"allowedCommonJsDependencies":` `["pdfjs-dist"],`

Check the project angular.json for more useful configuration
